 [[headers]]
  for = "*/"

  [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = "default-src 'self';"
      Content-Security-Policy = "frame-ancestors 'none'"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200