 [[headers]]
  for = "*/"

  [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options: nosniff
      Content-Security-Policy = "default-src 'none'; font-src https://fonts.googleapis.com; img-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'; frame-ancestors 'none'; "
      

[[redirects]]
  from = "/*"
  to = "/"
  status = 200