 [[headers]]
  for = "*/"

  [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options= "nosniff"
      Content-Security-Policy = "default-src 'self'; font-src https://fonts.googleapis.com https://fonts.gstatic.com ; img-src 'self'; object-src 'none'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; frame-ancestors 'none'; "
      

[[redirects]]
  from = "/*"
  to = "/"
  status = 200